[default]
address = "0.0.0.0"
port = 2345

[global.databases]
postgres_logs = { url = "postgres://olrgcqvsjinszb:9d8b4e1fa5caff78a989dd688c88e53abcef562931e8c5057cbaf128fe6ed49f@ec2-3-227-149-67.compute-1.amazonaws.com:5432/ddms2julrnbips" }